# Generated by Django 5.1.2 on 2024-10-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_product_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
    ]
